# Generated by Django 5.0.6 on 2024-08-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_produto_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
