# Generated by Django 5.0.6 on 2024-09-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="endereco",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
