# Generated by Django 5.0.6 on 2024-09-06 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_pedido_endereco"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="produto",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.produto"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.categoria"
            ),
        ),
    ]
