# Generated by Django 5.0.6 on 2024-09-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_pedido_produto_alter_produto_categoria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="valor",
        ),
    ]
